### ISSUE TITLE
BankCheck识别银行卡类别问题

### ISSUE THREAD

**Issue by Qdafengzi** [AbrahamCaiJin/CommonUtilLibrary#11]
开头406252的光大银行借贷卡识别不出来，什么也没返回

**Comment by AbrahamCaiJin** [comment]
/*
 * 银行卡是由”发卡行标识代码 + 自定义 + 校验码 “等部分组成的 BIN号 银联标准卡与以往发行的银行卡最直接的区别就是其卡号前6位数字的不同。
 * 银行卡卡号的前6位是用来表示发卡银行或机构的，称为“发卡行识别码”(Bank Identification Number，缩写为“BIN”)。
 * 银联标准卡是由国内各家商业银行
 * (含邮储、信用社)共同发行、符合银联业务规范和技术标准、卡正面右下角带有“银联”标识(目前，新发行的银联标准卡一定带有国际化的银联新标识
 * ，新发的非银联标准卡使用旧的联网通用银联标识)、 卡号前6位为622126至622925之一的银行卡，是中国银行卡产业共有的民族品牌。
 */
