### ISSUE TITLE
AppCahce 的key问题

### ISSUE THREAD

**Issue by LuckyJayce** [AbrahamCaiJin/CommonUtilLibrary#14]
private File newFile(String key) {
            return new File(cacheDir, key.hashCode() + "");
     }

不同String的hashCode是会重复的

**Comment by AbrahamCaiJin** [comment]
![image](https://user-images.githubusercontent.com/15973675/28447455-6c017054-6e03-11e7-9039-2d4a7c90d408.png)
![image](https://user-images.githubusercontent.com/15973675/28447462-7918fb54-6e03-11e7-9d7f-42c375115ed2.png)
都会存在的

**Comment by LuckyJayce** [comment]
“Aa“和”BB“的hashcode一样
如果key为“Aa“的取到了之前key为”BB“存的缓存，这不是有问题么？

**Comment by AbrahamCaiJin** [comment]
这个问题避免不了吧？不管怎么做都是存在的，就像HashMap一样

**Comment by LuckyJayce** [comment]
难道key不是唯一值么？用key做为文件的文件名，不就不重复了
也可以key md5以下防止key的暴露

**Comment by LuckyJayce** [comment]
hashMap 的设计是相同的hashcdoe值放在同一个hash桶里，通过key找到对应的hash桶，然后桶里通过key找出相同key的值

**Comment by AbrahamCaiJin** [comment]
你的意思是存的时候用文件名存吗？或者md以后再作为key使用吗？

**Comment by LuckyJayce** [comment]
private File newFile(String key) {
        return new File(cacheDir, md5(key));
 }

**Comment by AbrahamCaiJin** [comment]
好的，谢谢大佬指导

**Comment by AbrahamCaiJin** [comment]
大佬，你看看还有没有什么其他不对的地方，直接pull上来吧，多谢大佬
