### ISSUE TITLE
一点想法

### ISSUE THREAD

**Issue by hippyk** [AbrahamCaiJin/CommonUtilLibrary#17]
感觉这种直接copy需要的代码更方便快捷，往往引入整个包，其实能用上的方法可能也就一两个。

**Comment by AbrahamCaiJin** [comment]
对，刚开始我也是这么做的，所以加上了一些自定义view之类的，但是又有很多人给我说这样不方便，所以我就去掉了一些控件view，上传了jcenter，所以还是根据自己的习惯来吧。

**Comment by AbrahamCaiJin** [comment]
如果你项目中有什么用到的好的工具类，可以上传上来一起共享哟，一起维护
