### ISSUE TITLE
大神  在线工具有没有那种pl/sql里面已经美化的语句,转成java ,stringbuild.append()那种的啊,有没有啊地址发我419704299@qq.com

### ISSUE THREAD

**Issue by tangchao0106** [AbrahamCaiJin/CommonUtilLibrary#18]
大神  在线工具有没有那种pl/sql里面已经美化的语句,转成java ,stringbuild.append()那种的啊,有没有啊地址发我419704299@qq.com

**Comment by AbrahamCaiJin** [comment]
不知道你说的什么意思？你看看这个http://tool.lu/

**Comment by tangchao0106** [comment]
这个地址看过了没有啊,类似与这种	pl/sql里面的sql美化过,然后转成java语句,我不想一句句自己加	sb.append啊
有没有这样的工具啊
StringBuilder sb = new StringBuilder();
		sb.append(" select qxbh ,DZORXLMC,QXBW,QXNR,dzorxl,QXZSBMC,");

**Comment by AbrahamCaiJin** [comment]
你可以试试用正则来做，或者去看看Navicat好像可以复制java格式
