### ISSUE TITLE
CloseIO 方法没有

### ISSUE THREAD

**Issue by lcqbug** [AbrahamCaiJin/CommonUtilLibrary#21]
FileUtils 中有个 CLoseIO 方法, 引入的是 import static com.jingewenku.abrahamcaijin.commonutil.AppFileMgr.closeIO;  然而 AppFileMgr 并没有这个类或方法

**Comment by AbrahamCaiJin** [comment]
你是用的compile依赖吗？这个我上传git了，忘了更新jcenter了，不好意思

**Comment by Freshman111** [comment]
closeIO这个方法好像还是没有啊
