### ISSUE TITLE
getStringFromFile  

### ISSUE THREAD

**Issue by lcqbug** [AbrahamCaiJin/CommonUtilLibrary#22]
Fileutiles 中  getStringFromFile 方法中convertStreamToString()方法不存在

public static String convertStreamToString(InputStream is) {      
        /*  
          * To convert the InputStream to String we use the BufferedReader.readLine()  
          * method. We iterate until the BufferedReader return null which means  
          * there's no more data to read. Each line will appended to a StringBuilder  
          * and returned as String.  
          */     
         BufferedReader reader = new BufferedReader(new InputStreamReader(is));      
         StringBuilder sb = new StringBuilder();      
     
         String line = null;      
        try {      
            while ((line = reader.readLine()) != null) {      
                 sb.append(line + "\n");      
             }      
         } catch (IOException e) {      
             e.printStackTrace();      
         } finally {      
            try {      
                 is.close();      
             } catch (IOException e) {      
                 e.printStackTrace();      
             }      
         }      
     
        return sb.toString();      
     }

**Comment by AbrahamCaiJin** [comment]
github上有的，jcenter忘了更新了
