### ISSUE TITLE
CommonUtil模块下的AndroidManifest.xml文件内，权限申明位置有误

### ISSUE THREAD

**Issue by artshell** [AbrahamCaiJin/CommonUtilLibrary#24]
`<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />`
不应该声明在application 标签内，在 android studio 3.0 编译时出现错误

**Comment by AbrahamCaiJin** [comment]
好的，谢谢指出！

**Comment by artshell** [comment]
@AbrahamCaiJin 什么时候发布aar

**Comment by AbrahamCaiJin** [comment]
已经发布呢

**Comment by artshell** [comment]
还是 1.0.1啊

**Comment by AbrahamCaiJin** [comment]
哦，声明权限错误这里没改，那我明后天发吧

**Comment by artshell** [comment]
嗯，谢谢，幸苦

**Comment by AbrahamCaiJin** [comment]
没事，多谢指出，可能还有很多问题，大家一起完善
