### ISSUE TITLE
在gradle里添加依赖后报错

### ISSUE THREAD

**Issue by AuxLuffy** [AbrahamCaiJin/CommonUtilLibrary#25]
module下build.gradle中：compile 'com.abrahamcaijin.commonutil:CommonUtil:1.0.2'
erro: unknown element <uses-permission> found.
应该是你的库中清单文件下的application节点下的一段话导致出现的这个bug，<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />

**Comment by AbrahamCaiJin** [comment]
![image](https://user-images.githubusercontent.com/15973675/34476618-533c0fb0-efcd-11e7-8199-a4a4b7e9cd08.png)
啥也没有呀！
