### ISSUE TITLE
Android Studio3.1 gradle4.4 会出现问题error: unknown element <uses-permission> found.

### ISSUE THREAD

**Issue by mcxinyu** [AbrahamCaiJin/CommonUtilLibrary#28]
error: unknown element <uses-permission> found.
Message{kind=ERROR, text=error: unknown element <uses-permission> found., sources=[C:\Users\mcxin\Documents\CodeHub\NJFANDROID\app\build\intermediates\manifests\full\njfBeta\debug\AndroidManifest.xml:874], original message=, tool name=Optional.of(AAPT)}

**Comment by mcxinyu** [comment]
![image](https://user-images.githubusercontent.com/9566116/38715127-f9984710-3f0b-11e8-9fd2-73974133ab0a.png)

**Comment by AbrahamCaiJin** [comment]
好久没上来了。。。
打开gradle.properties添加下面代码即可解决：
android.enableAapt2=false
 
还有权限要在application前面加

**Comment by AbrahamCaiJin** [comment]
或者我没回复，你急着用的话，就把需要用的哪个拷贝到自己的工具包里面，方便快捷！！！

**Comment by mcxinyu** [comment]
android.enableAapt2=false 我之前试过这个方式，但是运行的时候会出现其他错误。
我的所有权限都是写在application前面的，只有引用了本库才会出错。
