### ISSUE TITLE
AndroidManifest中application下不应该存在权限的注册

### ISSUE THREAD

**Issue by gongjie** [AbrahamCaiJin/CommonUtilLibrary#29]
权限的注册不应该存在AndroidManifest中application下，而应该在application外面.

**Comment by AbrahamCaiJin** [comment]
多谢提醒，这个前面改了忘了提交了，我想请问一下我看好多其他库的权限都是使用者自己添加的，这个权限是让使用者自己添加还是集成到库里面比较好？

**Comment by gongjie** [comment]
使用者既然使用第三方库，肯定是为了少写代码，所以集成到库里面应该好点。
