### ISSUE TITLE
权限冲突

### ISSUE THREAD

**Issue by zhoukeep** [AbrahamCaiJin/CommonUtilLibrary#33]
error: unknown element <uses-permission> found.

Message{kind=ERROR, text=error: unknown element <uses-permission> found., sources=[/Users/liangzhou/Documents/GitStore/Android-Group/AndroidWallet/app/build/intermediates/manifests/full/debug/AndroidManifest.xml:125], original message=, tool name=Optional.of(AAPT)}

**Comment by AbrahamCaiJin** [comment]
新版本已解决，最好是改为本地依赖最好，方便修改
