### ISSUE TITLE
AAPT: error: unexpected element <uses-permission> found in <manifest><application>.

### ISSUE THREAD

**Issue by xzg8023** [AbrahamCaiJin/CommonUtilLibrary#39]
引入该库后提示：
`AAPT: error: unexpected element <uses-permission> found in <manifest><application>.`
去除该库后，正常，多次验证确实是引入该库导致的问题。
我这边打开本地下载的CommonUtilLibrary库的配置文件如下：
`<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.jingewenku.abrahamcaijin.commonutil"
    android:versionCode="1"
    android:versionName="1.0" >

    <uses-sdk
        android:minSdkVersion="12"
        android:targetSdkVersion="25" />

    <application
        android:allowBackup="true"
        android:label="@string/app_name"
        android:supportsRtl="true" >
        <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    </application>

</manifest>`

以上配置中的读写权限语句，放错位置了，导致编译提示错误，提示：
`AAPT: error: unexpected element <uses-permission> found in <manifest><application>.`
不清楚以上的权限语句是如何生成的，我这边看库的源码并未发现相关的语句
另外，该库1.0.0版本我这边也有问题，该库使用被引用次数蛮多的，不应该出现这样的问题，可能是我这边的其它配置，或环境问题？？？

我这边依赖的版本有：1.0.2，和 1.0.0 都有以上的问题，还望帮忙看一下
` implementation 'com.abrahamcaijin.commonutil:CommonUtil:1.0.2'`

**Comment by xzg8023** [comment]
新建项目，引入该库后出现同样的问题，合并后的配置文件，同样在错误的位置出现了
`
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
`；导致编译异常；
环境：
kotlin：1.3.50
build:gradle:3.5.2
as：3.5.2
compileSdkVersion：28

**Comment by AbrahamCaiJin** [comment]
好的，收到问题，这个看你急不急用了，急用的话，我可以先升级一个版本，这个问题是因为以前的工具查不严谨，所以用起来没问题，后面的版本高了，所以才有这个问题，或者你还可以直接下载依赖库到本地进行依赖。

**Comment by AbrahamCaiJin** [comment]
禁用AAPT应该也能解决

**Comment by AbrahamCaiJin** [comment]
我这里发布新版本，内部已经测试生效了，看看你那里可以了不，不行的话就需要等待通过审核，要不了多长时间的
