### ISSUE TITLE
单例double-check少了一个关键字

### ISSUE THREAD

**Issue by huclengyue** [AbrahamCaiJin/CommonUtilLibrary#4]
看到很多用到单例的类中使用了double-check

在变量生命中少了一个关键字  `volatile `

**Comment by AbrahamCaiJin** [comment]
这个看个人的写法，一般是没有，但是上次了各种单例的写法，最好的单例是有的

**Comment by huclengyue** [comment]
不加`volatile`会存在空指针风险。double-check 都应该加上`volatile`
