### ISSUE TITLE
isPhone

### ISSUE THREAD

**Issue by LiJoeAllen** [AbrahamCaiJin/CommonUtilLibrary#42]
199开头的手机号不合法？

**Comment by AbrahamCaiJin** [comment]
应该是后面官方有些更新，这个你要去官网上查一查，以官方公布为准




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "AbrahamCaiJin/CommonUtilLibrary"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月14日(星期四) 下午4:26
收件人:&nbsp;"AbrahamCaiJin/CommonUtilLibrary"<CommonUtilLibrary@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[AbrahamCaiJin/CommonUtilLibrary] isPhone (#42)





 
199开头的手机号不合法？
