### ISSUE TITLE
checkBankCard       : 校验银行卡卡号是否合法，输入银行卡检验就crash

### ISSUE THREAD

**Issue by ll418718** [AbrahamCaiJin/CommonUtilLibrary#8]
![image](https://user-images.githubusercontent.com/21256291/28254122-6750476c-6adc-11e7-9bf4-ae97351c75e4.png)

**Comment by AbrahamCaiJin** [comment]
请问你用的是什么银行卡号呢？

**Comment by ll418718** [comment]
中国工商

**Comment by AbrahamCaiJin** [comment]
麻烦卡号可以借给我用一个吗

**Comment by ll418718** [comment]
现在又可以了，不好意思，我的问题

**Comment by ll418718** [comment]
有个建议 getNameOfBank 这个方法如果不输入6位数直接crash，这样做很不友好

**Comment by AbrahamCaiJin** [comment]
好的，后面有时间会考虑做一下
